# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01d0e003beff6f54e1ee1c65b1f09730"
name = "VIBEN'AURA Manager"
handle = "vibenaura-manager
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
